-- Orbitra social profiles. Run once in Supabase Dashboard -> SQL Editor.
create table if not exists public.orbitra_profiles (
  user_id uuid primary key,
  username text not null,
  avatar_path text,
  banner_path text,
  description text not null default '' check (char_length(description) <= 240),
  favorite_server text,
  favorite_server_name text,
  profile_status text not null default 'online' check (profile_status in ('online','dnd','invisible')),
  share_current_server boolean not null default false,
  current_server text,
  current_server_name text,
  presence_updated_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.orbitra_friendships (
  requester_id uuid not null,
  addressee_id uuid not null,
  status text not null default 'pending' check (status in ('pending', 'accepted')),
  created_at timestamptz not null default now(),
  primary key (requester_id, addressee_id),
  check (requester_id <> addressee_id)
);

create table if not exists public.orbitra_invites (
  id bigint generated by default as identity primary key,
  sender_id uuid not null, recipient_id uuid not null, server_address text not null,
  server_name text, seen boolean not null default false,
  created_at timestamptz not null default now(), expires_at timestamptz not null default (now() + interval '10 minutes')
);

alter table public.orbitra_profiles enable row level security;
alter table public.orbitra_friendships enable row level security;
alter table public.orbitra_invites enable row level security;
create policy "Profiles readable" on public.orbitra_profiles for select using (true);
create policy "Profiles writable" on public.orbitra_profiles for insert with check (true);
create policy "Profiles updateable" on public.orbitra_profiles for update using (true);
create policy "Friendships readable" on public.orbitra_friendships for select using (true);
create policy "Friendships creatable" on public.orbitra_friendships for insert with check (true);
create policy "Friendships updateable" on public.orbitra_friendships for update using (true);
create policy "Friendships removable" on public.orbitra_friendships for delete using (true);
grant select, insert, update on public.orbitra_profiles to anon, authenticated;
grant select, insert, update, delete on public.orbitra_friendships to anon, authenticated;
create policy "Invites readable" on public.orbitra_invites for select using (true);
create policy "Invites creatable" on public.orbitra_invites for insert with check (true);
create policy "Invites updateable" on public.orbitra_invites for update using (true);
grant select, insert, update on public.orbitra_invites to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('orbitra-avatars', 'orbitra-avatars', true, 2097152, array['image/png','image/jpeg'])
on conflict (id) do update set public=true, file_size_limit=2097152, allowed_mime_types=array['image/png','image/jpeg'];
drop policy if exists "Avatars readable" on storage.objects;
drop policy if exists "Avatars uploadable" on storage.objects;
drop policy if exists "Avatars updateable" on storage.objects;
drop policy if exists "Avatars removable" on storage.objects;
create policy "Avatars readable" on storage.objects for select using (bucket_id='orbitra-avatars');
create policy "Avatars uploadable" on storage.objects for insert with check (bucket_id='orbitra-avatars');
create policy "Avatars updateable" on storage.objects for update using (bucket_id='orbitra-avatars') with check (bucket_id='orbitra-avatars');
create policy "Avatars removable" on storage.objects for delete using (bucket_id='orbitra-avatars');

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('orbitra-profile-media', 'orbitra-profile-media', true, 4194304, array['image/png','image/jpeg'])
on conflict (id) do update set public=true, file_size_limit=4194304, allowed_mime_types=array['image/png','image/jpeg'];
create policy "Profile media readable" on storage.objects for select using (bucket_id='orbitra-profile-media');
create policy "Profile media uploadable" on storage.objects for insert with check (bucket_id='orbitra-profile-media');

create index if not exists orbitra_profiles_username_idx on public.orbitra_profiles(lower(username));
create index if not exists orbitra_friendships_addressee_idx on public.orbitra_friendships(addressee_id, status);
