-- Profile statuses and server invitations for Orbitra 0.44 development build.
alter table public.orbitra_profiles add column if not exists profile_status text not null default 'online';
alter table public.orbitra_profiles drop constraint if exists orbitra_profiles_profile_status_check;
alter table public.orbitra_profiles add constraint orbitra_profiles_profile_status_check check (profile_status in ('online','dnd','invisible'));
create table if not exists public.orbitra_invites (
 id bigint generated by default as identity primary key, sender_id uuid not null, recipient_id uuid not null,
 server_address text not null, server_name text, seen boolean not null default false,
 created_at timestamptz not null default now(), expires_at timestamptz not null default (now() + interval '10 minutes')
);
alter table public.orbitra_invites enable row level security;
drop policy if exists "Invites readable" on public.orbitra_invites;
drop policy if exists "Invites creatable" on public.orbitra_invites;
drop policy if exists "Invites updateable" on public.orbitra_invites;
create policy "Invites readable" on public.orbitra_invites for select using (true);
create policy "Invites creatable" on public.orbitra_invites for insert with check (true);
create policy "Invites updateable" on public.orbitra_invites for update using (true);
grant select, insert, update on public.orbitra_invites to anon, authenticated;
