-- Unified player/theme reports for Orbitra.
-- NOTE: the current launcher uses an anonymous Supabase key. The SELECT policy is therefore
-- client-gated, not cryptographically moderator-only. Replace it with authenticated JWT claims
-- before enabling moderation for third-party builds.
create table if not exists public.orbitra_moderation_reports (
 id bigint generated by default as identity primary key,
 reporter_id uuid not null,
 target_type text not null check (target_type in ('player','theme')),
 target_id text not null,
 target_name text,
 reason text not null check (char_length(reason) between 5 and 500),
 status text not null default 'open' check (status in ('open','resolved','rejected')),
 moderator_id uuid,
 created_at timestamptz not null default now(),
 resolved_at timestamptz
);
alter table public.orbitra_moderation_reports enable row level security;
drop policy if exists "Moderation reports creatable" on public.orbitra_moderation_reports;
create policy "Moderation reports creatable" on public.orbitra_moderation_reports for insert with check (true);
revoke select, update on public.orbitra_moderation_reports from anon, authenticated;
grant insert on public.orbitra_moderation_reports to anon, authenticated;
