-- Orbitra Theme Workshop. Run once in Supabase Dashboard -> SQL Editor.
create extension if not exists pgcrypto;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('theme-workshop', 'theme-workshop', true, 20971520, array['application/zip'])
on conflict (id) do update set public = true, file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.workshop_themes (
  id uuid primary key default gen_random_uuid(),
  author_user_id uuid not null,
  author_name text not null check (char_length(author_name) between 1 and 64),
  name text not null check (char_length(name) between 1 and 60),
  description text not null default '' check (char_length(description) <= 2000),
  version text not null default '1.0' check (char_length(version) <= 20),
  archive_path text not null unique,
  background text not null,
  surface text not null,
  accent text not null,
  text_color text not null,
  blur integer not null default 0 check (blur between 0 and 40),
  downloads integer not null default 0 check (downloads >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.theme_likes (
  theme_id uuid not null references public.workshop_themes(id) on delete cascade,
  user_id uuid not null,
  created_at timestamptz not null default now(),
  primary key (theme_id, user_id)
);

create table if not exists public.theme_comments (
  id bigint generated by default as identity primary key,
  theme_id uuid not null references public.workshop_themes(id) on delete cascade,
  user_id uuid not null,
  user_name text not null check (char_length(user_name) between 1 and 64),
  content text not null check (char_length(content) between 1 and 1000),
  created_at timestamptz not null default now()
);

alter table public.workshop_themes enable row level security;
alter table public.theme_likes enable row level security;
alter table public.theme_comments enable row level security;

drop policy if exists "Workshop themes are public" on public.workshop_themes;
create policy "Workshop themes are public" on public.workshop_themes for select using (true);
drop policy if exists "Anyone can publish a theme" on public.workshop_themes;
create policy "Anyone can publish a theme" on public.workshop_themes for insert with check (true);
drop policy if exists "Likes are public" on public.theme_likes;
create policy "Likes are public" on public.theme_likes for select using (true);
drop policy if exists "SS14 users can like" on public.theme_likes;
create policy "SS14 users can like" on public.theme_likes for insert with check (true);
drop policy if exists "SS14 users can unlike" on public.theme_likes;
create policy "SS14 users can unlike" on public.theme_likes for delete using (true);
drop policy if exists "Comments are public" on public.theme_comments;
create policy "Comments are public" on public.theme_comments for select using (true);
drop policy if exists "SS14 users can comment" on public.theme_comments;
create policy "SS14 users can comment" on public.theme_comments for insert with check (true);

drop policy if exists "Theme archives are public" on storage.objects;
create policy "Theme archives are public" on storage.objects for select using (bucket_id = 'theme-workshop');
drop policy if exists "Anyone can upload a theme archive" on storage.objects;
create policy "Anyone can upload a theme archive" on storage.objects for insert
  with check (bucket_id = 'theme-workshop' and (storage.foldername(name))[1] = 'themes');

create or replace function public.increment_theme_download(theme uuid)
returns void language sql security definer set search_path = public as $$
  update public.workshop_themes set downloads = downloads + 1 where id = theme;
$$;
grant execute on function public.increment_theme_download(uuid) to anon, authenticated;

grant select, insert on public.workshop_themes to anon, authenticated;
grant select, insert, delete on public.theme_likes to anon, authenticated;
grant select, insert on public.theme_comments to anon, authenticated;
grant usage, select on sequence public.theme_comments_id_seq to anon, authenticated;
