<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Launcher.props" />
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationIcon>../SS14.Launcher/Assets/icon.ico</ApplicationIcon>
    <AssemblyName>Orbitra_Launcher_Installer</AssemblyName>
    <RootNamespace>Orbitra.Installer</RootNamespace>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <TrimMode>partial</TrimMode>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <IlcOptimizationPreference>Size</IlcOptimizationPreference>
    <StackTraceSupport>false</StackTraceSupport>
    <EnableSourceLink>false</EnableSourceLink>
  </PropertyGroup>
  <ItemGroup><PackageVersion Remove="Microsoft.NET.ILLink.Tasks" /></ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Simple" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets/**" />
    <AvaloniaResource Include="**/*.xaml" />
    <Compile Update="**/*.xaml.cs"><DependentUpon>%(Filename)</DependentUpon></Compile>
  </ItemGroup>
</Project>
